### ISSUE TITLE
puppetbot invited every now and then

### ISSUE THREAD

**Issue by ar1a** [matrix-hacks/matrix-puppet-server#3]
in channels, puppetbot is invited until it rejects the invitation (timed out), and then is invited again. Happens every few minutes(?)

**Comment by Sorunome** [comment]
Yeah i'll just have puppetbot be in the room at all times instead

**Comment by Sorunome** [comment]
fixed in https://github.com/matrix-hacks/matrix-puppet-server/commit/f860c6857001dafd81ec12f1e350645199b32407
